update to tests

diff --git a/tests/tasks/example-gke-nat-gateway-regional.yaml b/tests/tasks/example-gke-nat-gateway-regional.yaml
--- a/tests/tasks/example-gke-nat-gateway-regional.yaml
+++ b/tests/tasks/example-gke-nat-gateway-regional.yaml
@@ -140,26 +140,30 @@ run:
     }
     EOF
     
-    # Run Terraform
-    terraform init -no-color -upgrade=true
-    terraform workspace select ${env_name} || terraform workspace new ${env_name}
-    terraform plan -lock=false -no-color
-    terraform apply -no-color -input=false -lock=false -auto-approve | tee ${EMAIL}/body-failed
+    # Apply and test function
+    function apply_and_run_test() {
+      terraform init -no-color -upgrade=true
+      terraform workspace select ${env_name} || terraform workspace new ${env_name}
+      terraform plan -lock=false -no-color
+      terraform apply -no-color -input=false -lock=false -auto-approve | tee ${EMAIL}/body-failed
 
-    # Test NAT Gateway
-    echo "" > ${EMAIL}/body-failed
-    export CLOUDSDK_CONTAINER_USE_V1_API_CLIENT=false
-    gcloud beta container clusters get-credentials ${CLUSTER_NAME} --region ${REGION}
-    NAT_IP=$(terraform output ip-nat-gateway)
-    count=0
-    EXTERNAL_IP=""
-    while [[ $count -lt 10 && "${NAT_IP}" != "$(tr -d '\r' <<<${EXTERNAL_IP})" ]]; do
-      EXTERNAL_IP=$(kubectl run example -i -t --rm --restart=Never --image centos:7 -- curl -s http://ipinfo.io/ip || true)
-      ((count=count+1))
-    done
-    test $count -lt 10
+      echo "" > ${EMAIL}/body-failed
+      export CLOUDSDK_CONTAINER_USE_V1_API_CLIENT=false
+      gcloud beta container clusters get-credentials ${CLUSTER_NAME} --region ${REGION}
+      NAT_IP=$(terraform output ip-nat-gateway)
+      count=0
+      EXTERNAL_IP=""
+      while [[ $count -lt 10 && "${NAT_IP}" != "$(tr -d '\r' <<<${EXTERNAL_IP})" ]]; do
+        EXTERNAL_IP=$(kubectl run example -i -t --rm --restart=Never --image centos:7 -- curl -s http://ipinfo.io/ip || true)
+        ((count=count+1))
+      done
+      test $count -lt 10
+    }
+    
+    # Run Terraform and tests
+    apply_and_run_test
 
-    ### Begin pull request test
+    ### Begin upgrade test
     if [[ "${git_src}" != "${git_target}" ]]; then
       
       PR_TEST_DIR="${BASE_DIR}/${git_target}/${example_dir}"
@@ -173,12 +177,5 @@ run:
       cd ${PR_TEST_DIR}
 
       ### Upgrade test
-      terraform init -no-color -upgrade=true
-      terraform workspace select ${env_name} || terraform workspace new ${env_name}
-      terraform plan -lock=false -no-color
-      terraform apply -no-color -input=false -lock=false -auto-approve | tee ${EMAIL}/body-failed
-
-      ### Clean apply test
-      terraform destroy -input=false -lock=false -auto-approve
-      terraform apply -no-color -input=false -lock=false -auto-approve | tee ${EMAIL}/body-failed
+      apply_and_run_test
     fi
