update to tests

diff --git a/tests/tasks/example-gke-nat-gateway-private.yaml b/tests/tasks/example-gke-nat-gateway-private.yaml
--- a/tests/tasks/example-gke-nat-gateway-private.yaml
+++ b/tests/tasks/example-gke-nat-gateway-private.yaml
@@ -137,24 +137,28 @@ run:
     }
     EOF
     
-    # Run Terraform
-    terraform init -no-color -upgrade=true
-    terraform workspace select ${env_name} || terraform workspace new ${env_name}
-    terraform plan -lock=false -no-color
-    terraform apply -no-color -input=false -lock=false -auto-approve | tee ${EMAIL}/body-failed
-
     # Test NAT Gateway
-    echo "" > ${EMAIL}/body-failed
-    gcloud container clusters get-credentials ${CLUSTER_NAME} --zone ${ZONE}
-    NAT_IP=$(terraform output ip-nat-gateway)
-    count=0
-    EXTERNAL_IP=""
-    while [[ $count -lt 3 && "${NAT_IP}" != "$(tr -d '\r' <<<${EXTERNAL_IP})" ]]; do
-      EXTERNAL_IP=$(kubectl run example -i -t --rm --restart=Never --image centos:7 -- curl -s http://ipinfo.io/ip || true)
-      ((count=count+1))
-    done
-    test $count -lt 3
+    function apply_and_run_test() {
+      terraform init -no-color -upgrade=true
+      terraform workspace select ${env_name} || terraform workspace new ${env_name}
+      terraform plan -lock=false -no-color
+      terraform apply -no-color -input=false -lock=false -auto-approve | tee ${EMAIL}/body-failed
 
+      echo "" > ${EMAIL}/body-failed
+      gcloud container clusters get-credentials ${CLUSTER_NAME} --zone ${ZONE}
+      NAT_IP=$(terraform output ip-nat-gateway)
+      count=0
+      EXTERNAL_IP=""
+      while [[ $count -lt 3 && "${NAT_IP}" != "$(tr -d '\r' <<<${EXTERNAL_IP})" ]]; do
+        EXTERNAL_IP=$(kubectl run example -i -t --rm --restart=Never --image centos:7 -- curl -s http://ipinfo.io/ip || true)
+        ((count=count+1))
+      done
+      test $count -lt 3
+    }
+
+    # Run Terraform and tests
+    apply_and_run_test
+    
     ### Begin pull request test
     if [[ "${git_src}" != "${git_target}" ]]; then
       
@@ -169,12 +173,9 @@ run:
       cd ${PR_TEST_DIR}
 
       ### Upgrade test
-      terraform init -no-color -upgrade=true
-      terraform workspace select ${env_name} || terraform workspace new ${env_name}
-      terraform plan -lock=false -no-color
-      terraform apply -no-color -input=false -lock=false -auto-approve | tee ${EMAIL}/body-failed
+      apply_and_run_test
 
       ### Clean apply test
       terraform destroy -input=false -lock=false -auto-approve
-      terraform apply -no-color -input=false -lock=false -auto-approve | tee ${EMAIL}/body-failed
+      apply_and_run_test
     fi
